# fly.toml app configuration file generated for fragrant-pond-5178 on 2023-07-31T08:04:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fragrant-pond-5178"
primary_region = "nrt"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_DEBUG = "false"
  APP_ENV = "production"
  APP_NAME = "Larabel"
  APP_URL = "https://fragrant-pond-5178.fly.dev"
  DB_CONNECTION = "pgsql"
  DB_DATABASE = "postgres"
  DB_HOST = "db.lgziwifqtuaghlitgipe.supabase.co"
  DB_PORT = "5432"
  DB_USERNAME = "postgres"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
